# Название рабочего процесса
name: Go

# Условие запуска
on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string
  # Запуск по событию "push" (заливка изменений в ветку)
  push:
    # Указывает, что нужно запускать рабочий процесс, только если событие относится к ветке main
    branches: [ "mac" ]
  # Запуск по событию "pull_request". Поле "types" не указано, поэтому учитываются события по открытию, переоткрытию пул-реквеста и изменению в ветке.
  pull_request:
    # Указывает, что нужно запускать рабочий процесс, только если событие относится к ветке main
    branches: [ "mac" ]
  
# Задания
jobs:
  # Задание с идентификатором "build"
  build:
    # Для запуска задания используется раннер "ubuntu-latest", что соответствует последней версии Ubuntu
    runs-on: ubuntu-latest

    # Шаги задания
    steps:
    # Первый шаг использует действие "actions/checkout@v3", которое извлекает репозиторий для дальнейшей работы с ним
    - uses: actions/checkout@v3

    # Шаг с именем "Set up Go"
    - name: Set up Go
      # Этот шаг использует действие "actions/setup-go@v4", которое установит Go в систему
      uses: actions/setup-go@v4
      # Для этого действия можно задать версию Go, которую надо установить
      with:
        go-version: '1.20'

    # Шаг с именем "Build"
    - name: Build
      # Этот шаг просто выполняет команду 'go build -v ./...'
      run: go build -v ./...

 # Шаг с именем "Test"
    - name: Test
      env:
        MY_VAR: Hi there! My name is
      # Этот шаг выполняет команду 'go test -v ./...'
      run: |
        go test -v ./...
        echo $MY_VAR
        echo The username is ${{ github.ref }}
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(inputs) }}
      run: echo "$STRATEGY_CONTEXT"
      
      
